version: '3.8'

services:
  web:
    build: ./
    command: python manage.py runserver 0.0.0.0:9000
    volumes:
      - ./:/usr/src/app/
    ports:
      - 9000:9000
    env_file:
      - ./.env
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres

volumes:
  postgres_data: