# Generated by Django 3.2.7 on 2021-09-26 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversor_moedas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversao',
            old_name='valor_convetido',
            new_name='valor_convertido',
        ),
    ]
