# Generated by Django 3.2.7 on 2021-09-26 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversor_moedas', '0003_auto_20210926_0830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversao',
            name='data_hora',
            field=models.DateField(auto_now=True),
        ),
    ]
