# Generated by Django 3.2.7 on 2021-09-27 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversor_moedas', '0003_alter_conversao_data_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversao',
            name='valor_convertido',
            field=models.FloatField(),
        ),
    ]
