# Generated by Django 3.2.7 on 2021-09-26 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversor_moedas', '0004_alter_conversao_data_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversao',
            name='valor_convertido',
            field=models.FloatField(null=True),
        ),
    ]
